### ISSUE TITLE
Check50 is not checking for spaces or punctuation marks in Vanity Plates

### ISSUE THREAD

**Issue by edumats** [cs50/problems#105]
In CS50P, in Vanity Plate project, I noticed that check50 is not testing for spaces or punctuation marks like ? or ! , although it is stated in the requirements:

- No periods, spaces, or punctuation marks are allowed.

For example, both inputs "CS50 P" and  "CS50?" should fail, but check50 is not checking for those conditions.

**Comment by CarterZenke** [comment]
Hi @edumats, I hope you'll forgive the belated reply—we've fixed this in an earlier update, #97.
