### ISSUE TITLE
test_bank.py issues

### ISSUE THREAD

**Issue by anastasiaruzmaikina** [cs50/problems#106]
CS50 check seems to grade incorrectly.
When I used pytest test_bank.py, it performed as expected when bank.py code was correct, and it performed as expected when bank.py code was altered by using $30 instead of $20 or by removing .lower()
However cs50 check does not recognize that the when the code of bank.py is altered, pytest test_bank.py raises exception. 
In addition, I had to include value() function above test_value() in order for cs50 check to recognize that if bank.py code is correct, then pytest test_bank.py raised no exceptions. (Without including value() function above test_value() function, cs50 graded "correct bank.py" code negatively. ) This was the case even so 
import bank
from bank import value
was already included in test_bank.py

**Comment by rongxin-liu** [comment]
Thank you for reporting, please send us your `test_bank.py` and `bank.py` files to sysadmins@cs50.harvard.edu. Please also note that during testing, check50 will not be using your `bank.py` file for evaluation.
