### ISSUE TITLE
pset2 substitution check50 overlook

### ISSUE THREAD

**Issue by soablackwhite** [cs50/problems#107]
When checking for repeating characters in the key, I multiplied their alphabetical orders thinking it must always be equal to 25! (number of letters in alphabet -1 factorial). It passed all the check50 tests, and it seemed intuitively correct at first, but mathematically it isn't. This is similar to a previous thread made about key sum.

A wrong testing key that would still pass this test is ABCDUBGHIJKLMNOPQRSTUVWXYZ (U and B repeat).

algorithm/pseudocode:
```c
        int _index = tolower(key[i]) - 97;
        //compute product of all nbrs
        if(_index != 0){
            productcheck *= _index;
        }
        //check if equal to 25!
```

**Comment by CarterZenke** [comment]
Hi @soablackwhite, we've addressed this with #116!
