### ISSUE TITLE
Plurality, Runoff & Tideman tests fail to catch direct comparison of strings in vote()

### ISSUE THREAD

**Issue by TwistedCrusader** [cs50/problems#121]
if  `if (candidates[i].name == name)` is used in vote for comparing the strings the test fails to catch this and gives a pass for the vote() test.

I suspect this is due to the hardcoding of the test data: e.g. `candidates[0].name = "Alice";` and `printf("%s", vote("Alice") ? "true" : "false");` the strings are "string literals" ( https://github.com/curiouskiwi/cs50x-help/blob/master/stringliteral.md )

The compiler will only place one copy of the string in memory and use that for all instances where it's needed, so the ptr for both the candidate name and the name passed to vote is the same.

**Comment by ghost** [comment]
(as mentionned, pull #122 fixes this issue)

**Comment by CarterZenke** [comment]
Fixed, thank you!
