### ISSUE TITLE
Finance testing impletation of lookup

### ISSUE THREAD

**Issue by Samartic** [cs50/problems#159]
The code we are testing ask an API to lookup if a stock is in a database and should return an error code if the symbol of the stocks in question arent there. BUT YOU ARe USING FAKE STOCK (AAAA, BBBB, CCCC) to test the validity of that funtion and yet de test is not pass because it dont find thoses stock

**Comment by rongxin-liu** [comment]
Using fake stock for testing doesn't matter. Please double-check your implementation.

**Comment by Samartic** [comment]
Thank you for your quick response ! I didn't expect to get answer before monday morning.

 I do understand your point and in a testing point of view it does make sense. And yes i will implement the code accordingly.

But if i may point out:
 The first requirement of buy is to return an apology if the lookup in the api return a none value, the assigment doesn't say in anyway that check50 and thus submit50 will use fake stock to evaluate nor the value they use. The check50 report doesn't show the value used either. I find it quite intense that to find out that my code was "ok" on that matter i had to basicly find your check50, validate manually the return in the api of your stock to find out that they aren't in the database (i had doubt looking at it, but wanted to make sure). And by intense, i mean compare to every other assigments.

Now i'm wandering why as i can see 3 solutions rapidly that would had prevent other students and myself to get throught all those step, and I'm confident that you thought about it as you propose one of them.

Oh wait ! Was that all planed?  Force us to find that github, look into your check50 to find what's happening ?  

In anyway continue your great work! CS50x made me learn so much and i don't regret any step of the way.
