### ISSUE TITLE
Test for "Re-requesting a Vanity Plate" excercise are not aligned with the description of the "Vanity Plate" excercise in Problem set 2

### ISSUE THREAD

**Issue by ellerysammy** [cs50/problems#182]
Description in Problem set 2 for vanity plates reads
“… vanity plates may contain a maximum of 6 characters (**letters or numbers**) and a minimum of 2 characters.”
"OR" means that it could be only letters(without numbers)

Doing check50 for test_plates I got
_:( test_plates catches plates.py without checks for number placement
    expected exit code 1, not 0_

_:( test_plates catches plates.py without checks for alphanumeric characters
    expected exit code 1, not 0_

**Comment by curiouskiwi** [comment]
That first test is for the number placement requirement from the spec:
> “Numbers cannot be used in the middle of a plate; they must come at the end.

The second test is for the "letters or numbers" only from the spec.  ie, no non-alphanumeric chars are allowed.

The check50 test will fail if your test_fuel.py does not catch a buggy solution that isn't following these rules.
