### ISSUE TITLE
finance check "handles valid ticker symbol" is actually using "invalid ticker symbol"

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/problems#218]
hi!

## Reason behind

![image](https://github.com/cs50/problems/assets/19423063/e4218fc0-5eec-421a-b870-a0683669b055)

* i navigated to the git blame view of the file defining those checks:

* there were only 2 recent commits by @ CarterZenke & @ curiouskiwi 
which were very small

* navigating past them, i noticed that most of the checks defined there were written by @brianyu28 in month of 2020 November.
https://github.com/cs50/problems/blame/bbc4dce5aad913a04fc2d6ff0092c3941d384616/finance/__init__.py#L90

* So, more than 3 years ago.

And it seems to me that:

* back then, the stock market api backend used was: the iexcloud.io 
i.e. the <code>Data provided by [IEX](https://iexcloud.io/)</code> part in the distribution code of the `layout.html`

* ... and that iex provided [example dummy requests]
similar to how `visa` has dummy cards in the `credit` pset, or the `stripe` payment gateway has dummy emails etc

* recently, the api backend was changed to yahoo finance; with which the dummy request no longer returns dummy data; but rather a `400`

* but the checks description were not updated to match that. that's what caused the problem.

[example dummy requests]: https://iexcloud.io/documentation/administration/access-and-security/use-an-api-token-in-api-docs-example-requests.html "API Docs Example Requests"

even the cs50's own implementation aka "staff solution" throws `400` error on running check50's data on it.

https://github.com/cs50/problems/assets/19423063/18b3fcd2-6b5b-42fe-9a32-ae82275dfe3d

## details

* the check50 is using the value `.quote("AAAA")` 
* which results in the `helpers.lookup()` url string to become:

```url
https://query1.finance.yahoo.com//v7/finance/download/AAAA?period1=1703103695&period2=1703708495&interval=1d&events=history&includeAdjustedClose=true
```

* or as shown in the console logs, the HTTP GET request to be:

```http
DEBUG: Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG: https://query1.finance.yahoo.com:443 "GET /v7/finance/download/AAAA?period1=1703103695&period2=1703708495&interval=1d&events=history&includeAdjustedClose=true HTTP/1.1" 404 52

```

which 
* being an invalid symbol, results in `404` from this yahoo api itself. and hence, 
* both - my implementation, and even cs50's own implementation at https://finance.cs50.net/buy rightly show `400` on it

when given a genuinely valid symbol like `nflx`:
* the yahoo api responds with correct data, and again, 
* both my as well as https://finance.cs50.net/buy show the data correctly.

now:
* if the ticker symbol is invalid/dummy, 
* the upstream yahoo api doesn't have any data on it, 
* so, how will any application show it as valid without comprimising with academic honesty 😃

https://github.com/cs50/problems/blob/5144d41e5cc83fe5708bfacce9f1811e897867c1/finance/__init__.py#L96C1-L105

**Comment by curiouskiwi** [comment]
@goyalyashpal what you may have missed is that `check50` uses its own specific lookup.py file and does not use the Yahoo api at all.  This is done so that we always know what the price will be.    So we don't need any changes.  Thanks for the effort though.

**Comment by goyalyashpal** [comment]
hi @curiouskiwi ! thanks a lot for sharing.

umh, my check50 report is failing. and i have now no clue why. 

'cz as shown in above screen recording, both in browser & in console with http status `200`  it is clearly working "on my system" lol

here's the link:
https://submit.cs50.io/check50/8ee4ad64886dc4fac29728a853fe20be3d18a6aa

**Comment by curiouskiwi** [comment]
More than likely, you haven't formatted *all* dollar values using the `usd` jinja filter, as described in the first Hint in the specification.  If that's not it, I'd suggest you post in one of [our communities](https://cs50.harvard.edu/x/communities) for further help.

**Comment by goyalyashpal** [comment]
ahwwww right. awesome. thanks a lot again.

_edit:_ yeah, it passes now. thanks a lot

> using the usd jinja filter, as described in the first Hint in the specification
