### ISSUE TITLE
Issue with tideman CS50!! error: :( lock_pairs skips final pair if it creates cycle

### ISSUE THREAD

**Issue by juancaiman** [cs50/problems#221]
Hey there!

I've been struggling with this section for a couple of days, but now I feel there's some issue I can't figure out. In the `lock_pairs` function, I did find the logic behind it and created a function that works in every case I tried it (with middle and final cycles, so skipping those), but I always get the error: ":( lock_pairs skips final pair if it creates a cycle." Is there a specific case scenario I'm not seeing? I read somewhere about "fork cases," but I don't know a case for those to try with my code. So if someone could help, it would be amazing.

A few things:
1) My code is a mess because I'm just learning, a total newbie, so be nice but criticize it, of course!
2) I'm not looking for answers because I want to learn my own way, so I'm not looking for code, but maybe a case scenario that I can use for this situation.
3) I know the solution here was way easier with a recursive function, but I still found it hard to grasp all the edges of the concept. It took me a whole day just to do the 'atoi' exercise, so I did my own "recursive...ish" way but just with if cases scenarios.

this is the code:

void lock_pairs(void) 
{

 //main int for looping
    int t = 0;

    //scenario no pair
      if( pair_count == 0)
    {
        return;
    }

    //scenario single pair
      if( pair_count < 2 && pair_count > 0)
    {
        locked[pairs[t].winner][pairs[t].loser] = true;
        return;
    }

    //scenario for 2 pairs
     if( pair_count < 3 && pair_count > 1)
     {
        while (t < 2)
        {
            locked[pairs[t].winner][pairs[t].loser] = true;
            t++;
        }
        return;
     }

        //multiple pairs scenario
    if(pair_count > 2)
    {
        //lock always first too pairs
    while( t < 2)
    {
        locked[pairs[t].winner][pairs[t].loser] = true;
        printf("lock: winner %i, loser %i \n", pairs[t].winner,pairs[t].loser); //quitar
        t++;
    }
    //int t store main pair info, int p for looping in each case, and h for finding winners.
    int p = t;//
    int h = t;

    //iteration
    while (t < pair_count)
    {
        while (h >= 0)
        {
            // loser has been winner before?
            while(pairs[p].loser != pairs[h].winner && h >= 0)
            {
                h--;
            }
            //if it has and his loser is t, its a cycle. dont lock an continues.
            if(pairs[p].loser == pairs[h].winner && pairs[h].loser == pairs[t].winner && locked[pairs[h].winner][pairs[h].loser] == true)
            {
                t++;
                p = t; //nest pair
                h = t; // reset h
                break;
            }
            //if it has but loser not t, no cycle ...yet. "recursion ish" check next line.
            else if(pairs[p].loser == pairs[h].winner && pairs[h].loser != pairs[t].winner && locked[pairs[h].winner][pairs[h].loser] == true)
            {
                p = h; // p store h
                h = t;// reset h
                break;
            }
            //if has never won. lock pair.
            else
            {
                locked[pairs[t].winner][pairs[t].loser] = true;
                printf("lock: winner %i, loser %i \n", pairs[t].winner,pairs[t].loser); //quitar
                t++;
                p = t; //next pair
                h = t; // reset h
                break;
            }
        }

    }
    }
    return;
}

thanks!!!!

**Comment by dmalan** [comment]
For questions on problem sets or labs, best to post in any of CS50's communities, https://cs50.harvard.edu/x/communities/!
