### ISSUE TITLE
CS50P: Week 6 Pset: "Lines of code" - Check50 does not pass on two-thousand-fifty-eight.py

### ISSUE THREAD

**Issue by Asha-Srikanth** [cs50/problems#225]
My program passes all conditions on Check50, except for 1. 
Could it be possible that someone edited the file 'two-thousand-fifty-eight.py' ??

![image](https://github.com/cs50/problems/assets/146133807/51bcd3ea-1118-4699-932c-532355231667)

My program gives an output of extra 4 lines. [I thoroughly tested my program on my other local programs and there were no issues]
![image](https://github.com/cs50/problems/assets/146133807/2105798b-dd48-4d86-9fd3-e2dd993869d2)

**Comment by curiouskiwi** [comment]
The file is correct.  I'd suggest that your program is counting lines that perhaps have multiple whitespace characters.  If you are still unsure, best to post in one of our [communities](https://cs50.harvard.edu/python/communities) for more help.
