### ISSUE TITLE
Check50 is checking the wrong code

### ISSUE THREAD

**Issue by WDYC2003** [cs50/problems#237]
I want to check an assignment using check50, but it keeps checking a different code for a different assignment. How can I correct this?

**Comment by rongxin-liu** [comment]
Can you please describe the issue in detail and attach screenshots?

**Comment by WDYC2003** [comment]
![image](https://github.com/cs50/check50/assets/94567618/9193f033-f98a-4099-982d-398cf59e972b)
I want the code to check name.c, but it keeps checking hello.c. This wasn't an issue with the other assignments, they were both verified normally.

**Comment by rongxin-liu** [comment]
Thanks for attaching the screenshot.

This wasn't a check50 issue and the check50 check is indeed looking for `hello.c`, not `name.c`.

**Comment by WDYC2003** [comment]
Apologies, but I would like some clarifications on how exactly to guide cs50 into checking the correct file, as I cannot submit it or check it in any way due to this.

**Comment by curiouskiwi** [comment]
@WDYC2003  Please follow the instructions for the problem set exactly.  Your file should be called `hello.c` in a folder called `me`  with the check50 instruction  `check50 cs50/problems/2024/x/me`      If you have further questions or need more help, please ask in one of our communities (https://cs50.harvard.edu/x/communities)
