### ISSUE TITLE
check50 cs50/problems/2024/x/world

### ISSUE THREAD

**Issue by AnyutaGartsueva** [cs50/problems#240]
My "hello.c" cannot be apploaded through "check50 cs50/problems/2024/x/world" command. The terminal gives me the answer "Missing environment variable CS50_TOKEN". What can I do? And what kind of token is that? Could you tell me?

**Comment by rongxin-liu** [comment]
Please visit https://cs50.dev/restart and see if that works. For technical issue, please email sysadmins@cs50.harvard.edu.
