### ISSUE TITLE
#include <cs50.h>, No rules to target mario

### ISSUE THREAD

**Issue by AnyutaGartsueva** [cs50/problems#241]
The online compiler does not like #include <cs50.h> in my code.

The VS says "No rules to target mario" when I try to compile the file (with "make mario"). But the fine exists.

What do I need to do?

**Comment by rongxin-liu** [comment]
For technical issue, please email sysadmins@cs50.harvard.edu!

**Comment by rongxin-liu** [comment]
This repository is not the place to post technical issues. Thank you!
