### ISSUE TITLE
CS50P Problem Set 8 - test_jar - check50 method `test_number_functions()` may fail on test counts larger than 9 and ending with 3 or less

### ISSUE THREAD

**Issue by kguryanov** [cs50/problems#247]
## Steps to reproduce:

1. Create 23 tests in your test_jar.py
2. Run check50 cs50/problems/2022/python/jar

## Actual result:

1. check50 fails for the last test ":( test_jar.py contains at least four functions".
  
   ![image](https://github.com/cs50/problems/assets/3843209/f503cce2-997d-4b13-9e19-e12d5f5ace08)

## Expected result:

1. check50 validation must succeed since the problem set requirement is satisfied.    

   ![image](https://github.com/cs50/problems/assets/3843209/162db3b5-97d1-4cba-855b-349010157923)

## Possible solution:

1. Add `+` token to the regex expression `matches = re.search(r'(\d+) passed', out)`: 
    
    ![image](https://github.com/cs50/problems/assets/3843209/79002bda-a269-4422-a429-a02f2d935564)

## NOTES:
The regex for parsing pytest output  -  [`matches = re.search(r'(\d) passed', out)`](https://github.com/cs50/problems/blob/6728ebf34755c1c1e833aebb97090cb08f0e8d6d/jar/__init__.py#L64) - only captures 1 digit in the capturing group:

   ![image](https://github.com/cs50/problems/assets/3843209/75570a1a-db76-41e4-9f6c-afc7e4c417b9)

 The number of test is parsed into variable and is checked against expected number of 4 test functions:

```python
    if not matches:
        raise check50.Failure("Could not parse output of pytest")
    try:
        functions = int(matches.groups(1)[0]) # save number of tests
    except ValueError:
        raise check50.Failure("Could not parse output of pytest")
    if functions < 4:  # do the validation
        raise check50.Failure("test_jar.py does not contain at least four functions")
```
 So, pset test file with 23 tests will fail the validation since capturing group only catches the "3 passed" part of string "= 23 passed in 0.03s =":

## Workaround 
In case you have more that 9 tests, make sure you have test counts are in range [14 .. 19], [24 .. 29], etc.:

**Comment by patrickthornton** [comment]
right you are; should be fixed by https://github.com/cs50/problems/pull/262!
