### ISSUE TITLE
CS50P PSET1 Bank misses extra output

### ISSUE THREAD

**Issue by ZRexshima** [cs50/problems#257]
If the tested program outputs the correct amount as a response but then prints out another line, check50 marks it as passing. In the example found, during manual testing the program printed:

> $0
> $None

This still apparently passes check50. So check50 searches a regex for that line but misses the extra line.
My local test passed for 7/7 checks.

![check50-part2](https://github.com/cs50/problems/assets/29671149/79c6f5e3-f91a-46c9-a5ef-80519e8d3d16)

**Comment by ZRexshima** [comment]
Changing the return line of the regex function locally to the following seems to catch this and still passes my own solution code:
`return fr'^[^\d]*{escape(amount)}[^$\w]*$'`

**Comment by patrickthornton** [comment]
fixed by https://github.com/cs50/problems/pull/263; used a different regex, but it achieves the same result you're going for!
