### ISSUE TITLE
Substitution - Missing test for simple key sum

### ISSUE THREAD

**Issue by nicknapoli82** [cs50/problems#38]
I have observed that the substitution tests are passing an algorithm to detect duplicates in the key that is not totally correct.

The algorithm in question is simply to add each index in the `key` into a sum total variable, and check that the sum is equal to a hard coded number. Which in concept works. All of the provided keys on the cs50 problem description work using this algorithm. 
`NQXPOMAFTRHLZGECYJIUWSKDVB`  
`YTNSHKVEFXRBAUQZCLWDMIPGJO`  
`VcHpRzGjNtLsKfBdQwAxEuYmOi`  
As example. A simplified version of this algorithm is

```c
int sum = 0;
for(int i = 0; i < strlen(argv[1]); i++) {
    sum += tolower(argv[1][i]);
}
```

A key, though, that would appear correct to the algorithm that is clearly not is.
`oqsuwybdfhjlmnoqsuwybdfhjl`  

I'm writing out this issue simply in hopes that a check50 test can be created/changed in order to accommodate this simple algorithm issue. So that students taking the course do not trick themselves into believing their code is totally correct, when in reality it only works "most of the time."

I hope we can agree that check50 should provide a test that does not allow a simplified `key sum` algorithm to pass all the tests.

**Comment by CarterZenke** [comment]
Thanks, @nicknapoli82, and apologies for the quite belated reply. I believe we've addressed this with #125, if not in an earlier update.
