### ISSUE TITLE
Be more explicit about Tideman's specification regarding the use of global variables

### ISSUE THREAD

**Issue by nothingnesses** [cs50/problems#41]
I think Tideman's specification should explicitly state that the problem's test suite doesn't check the values of user-added global variables and that students shouldn't add/use their own global variables when writing their solution program because of that.

This is because I wrote a solution where I did use my own global variable and the program works properly, but fails the `check50` tests for `print_winner` because that test doesn't seem to use the `print_winner` function in the context of the whole program. I think it instead isolates it, whereas my implementation relies on computations done by previous functions and the value of my own global variable.

Alternatively, I think the problem's unit tests should be rewritten to take into account solutions like mine.

For more details, please see [a discussion about this I had on Discord](https://discord.com/channels/393846237255696385/637499924627456020/739853350392168529) with another student.

**Comment by brianyu28** [comment]
Hi @VoidNoire! The problem set specification already says:

> You should not modify anything else in `tideman.c` other than the implementations of the `vote`, `record_preferences`, `add_pairs`, `sort_pairs`, `lock_pairs`, and `print_winner` functions (and the inclusion of additional header files, if you’d like).

Given that global variables would require modify other parts of `tideman.c`, they're therefore not permitted.
