### ISSUE TITLE
potential PR re. pset4: recover

### ISSUE THREAD

**Issue by bolt-blue** [cs50/problems#43]
I was considering filing a pull request for this file: https://github.com/cs50/problems/blob/2020/x/recover/__init__.py

The purpose being, to add a second hash for each file in the case that someone checking or submitting versions of the .jpg's without the trailing zero bytes, would not fail.

However, when I checked the `sha256sum` of the jpg's that my code pulls from `card.raw` they do not match those in the file linked above.

Are `check50` and `submit50` using other code?

**Comment by curiouskiwi** [comment]
`check50` is testing against a different card.raw file so the hashes won't match what you may calculate using the rawfile given to you in the problem set.

**Comment by bolt-blue** [comment]
Thanks.
I didn't realise, until someone happened to share with me today the other .raw.
Feel free to link, or I'll go dig it up and see if I can put something together.

**Comment by curiouskiwi** [comment]
It's in the repo: https://github.com/cs50/problems/tree/2020/x/recover
