### ISSUE TITLE
check50

### ISSUE THREAD

**Issue by Nmartinezu** [cs50/problems#67]
error 

Make sure your username and/or password are valid and check50 is enabled for your account. To enable check50, please go to https://submit.cs50.io in your web browser and try again. If you're using GitHub two-factor authentication, you'll need to create and use a personal access token with the "repo" scope instead of your password. See https://cs50.ly/github-2fa for more information!

When check50 cs50/labs/2021/x/population and hello

**Comment by dmalan** [comment]
Be sure you've followed those steps!
