### ISSUE TITLE
Wrong suspect in fiftyville airports query leads to semantically weird results

### ISSUE THREAD

**Issue by lubianat** [cs50/problems#68]
If I search for a wrong suspect across passengers and airports, I get something like:

```
name | origin_airport_id | destination_airport_id | abbreviation | abbreviation | city | city | hour | day | month | year
Russell | 8 | 6 | CSF | BOS | Fiftyville | Boston | 16 | 29 | 7 | 2020
Russell | 7 | 8 | DXB | CSF | Dubai | Fiftyville | 16 | 30 | 7 | 2020
Russell | 8 | 5 | CSF | DFS | Fiftyville | Dallas | 10 | 30 | 7 | 2020
```

I do not know if that is a bug or a feature (or if I am missing something), but that led me to doubt what the tables really meant, as flying from DFS (Dallas) and  DXB (Dubai) in the same day _without_ an airport log of travel between both is... suspicious. 

I thought it was better to leave an issue just in case. 

SQL query = 
```
SELECT people.name, origin_airport_id, destination_airport_id,
origin.abbreviation, destination.abbreviation,
origin.city, destination.city,
hour, day, month, year FROM passengers
JOIN people ON passengers.passport_number = people.passport_number
JOIN flights ON passengers.flight_id = flights.id
JOIN airports AS origin ON origin.id = flights.origin_airport_id
JOIN airports AS destination ON destination.id = flights.destination_airport_id
WHERE people.id = "514354" and year = 2020;
```

**Comment by brianyu28** [comment]
Per the `origin_airport_id` and `destination_airport_id`, looks like Russell flew from Dubai to Fiftyville and then from Fiftyville to Dallas. This data is consistent with the mystery, though — you should be able to find other information from the database to help you determine who the thief is!
