### ISSUE TITLE
Check50 error/overlook for pset4:Filter

### ISSUE THREAD

**Issue by AdrianOles** [cs50/problems#73]
After completing the blur function in pset4, I came across an error/overlook in the blur check50. My function would find the correct pixel values, however, it mistakenly left a portion of the image black due to a parameter mistake in my code. (I wrote height instead of width for a loop parameter, so it stopped early.) Nonetheless, despite the mistake check50 marked my code correct because the tested images had equal dimensions, meaning width and height were the same, ie. (3x3), (4x4)... Although it is a very minuscule overlook/scenario, I thought it was worth mentioning to ensure the check50 test ensured the code was completely correct.

**Comment by CarterZenke** [comment]
Hi @AdrianOles! This should now be resolved with #127.
